.PHONY: clean All

All:
	@echo "----------Building project:[ leet-code - Debug ]----------"
	@"$(MAKE)" -f  "leet-code.mk"
clean:
	@echo "----------Cleaning project:[ leet-code - Debug ]----------"
	@"$(MAKE)" -f  "leet-code.mk" clean
