.PHONY: clean All

All:
	@echo "----------Building project:[ akuna_dev - Debug ]----------"
	@cd "akuna_dev" && "$(MAKE)" -f  "akuna_dev.mk"
clean:
	@echo "----------Cleaning project:[ akuna_dev - Debug ]----------"
	@cd "akuna_dev" && "$(MAKE)" -f  "akuna_dev.mk" clean
