.PHONY: clean All

All:
	@echo "----------Building project:[ interview_question - Debug ]----------"
	@cd "interview_question" && "$(MAKE)" -f  "interview_question.mk"
clean:
	@echo "----------Cleaning project:[ interview_question - Debug ]----------"
	@cd "interview_question" && "$(MAKE)" -f  "interview_question.mk" clean
